### ISSUE TITLE
'eval_select' is not an exported object from 'namespace:tidyselect'

### ISSUE THREAD

**Issue by jzadra** [r-lib/tidyselect#166]
I've included `tidyeval::eval_select()` per the instructions here: https://tidyselect.r-lib.org/articles/tidyselect.html

When I build/check the package locally, it works fine, but when TravisCI runs checks on the full package, it gives the following error:

'eval_select' is not an exported object from 'namespace:tidyselect'

https://github.com/sfirke/janitor/pull/328

**Comment by lionel-** [comment]
Did you add r-lib/tidyselect to `Remotes:` so Travis knows how to fetch the dev version? See https://github.com/r-lib/tidyselect/blob/76099387fc7db717cb3a66316f31964dd22f3e25/DESCRIPTION#L31

**Comment by lionel-** [comment]
I was planning to send tidyselect to CRAN today, but it might be delayed as it's waiting for a vctrs release to be accepted.

**Comment by sfirke** [comment]
Thanks Lionel for the update & advice re: adding remotes.  Re: janitor #328 above I think we'll wait for tidyselect to hit CRAN (sounds like that's very soon), then require tidyselect 1.0.0 in the next version janitor.

Do you see any major risk to requiring tidyselect 1.0.0, that is, might people not want to update their tidyselect because of the breaking changes?  I looked over the list of breaking changes and they seemed minor to me but thought I'd get your (better) perspective.

**Comment by lionel-** [comment]
There shouldn't be any problems with depending on tidyselect 1.0.0 :)
