### ISSUE TITLE
Revdep notes

### ISSUE THREAD

**Issue by hadley** [r-lib/tidyselect#312]
57 packages total

* Many failures from `all_of()`: need to deprecate `all_of()` must be used within a *selecting* function.` instead of erroring.
* Breakage in broom.helpers seems to affect a number of downstream packages
* Many failures due to tests that do `expect_warning(expr, NA)`

Fix first two and then re-run

**Comment by hadley** [comment]
* [ ] datawizard — https://github.com/easystats/datawizard/issues/267

**Comment by hadley** [comment]
After this batch probably need to rerun with tidyr revdeps too.

**Comment by larmarange** [comment]
So far, it was recommended in *Programming with dplyr* vignette (https://www.topbadges.fr/pins/1895-pins-rectangle-drapeau-japon.html) to use the syntax `.data$var` to avoid the "no visible binding" R CMD CHECK NOTE. 

With the evolution of `tidyselect`, what would be the recommendation?

**Comment by hadley** [comment]
That advice is only supposed to apply to data masking functions. For tidyselect you can just use strings.

**Comment by nucleic-acid** [comment]
Thanks for the reverse dependency checks and the proposed changes in https://github.com/nucleic-acid/namedropR/pull/56.

I recall getting errors complaining about "confusion with global variables" or similar, hence I had to use the .data$var syntax to pass checks. (Unfortunatley I don't recall the exact error message, maybe the same R CMD CHECK NOTE as mentioned by @larmarange ?)

Is that something, that will be fixed by the changes in tidyselect?

(relevant commit for reference: https://github.com/nucleic-acid/namedropR/commit/da08ce8d044a3cf9bf4aa28e8cc9573d2d15d5b8)

**Comment by hadley** [comment]
@nucleic-acid yes, because we now use strings instead of variable names. Updated dplyr docs at https://dplyr.tidyverse.org/dev/articles/programming.html#eliminating-r-cmd-check-notes
