### ISSUE TITLE
More context for errors

### ISSUE THREAD

**Issue by hadley** [r-lib/tidyselect#327]
e.g.

```R
pivot_longer(df, c(z = y))
#> Error in `build_longer_spec()`:
#> ! Can't rename variables in this context.
```

Maybe just needs an `error_arg`?

**Comment by lionel-** [comment]
hmm yes, and also pass the error call?

**Comment by hadley** [comment]
Error call is already there (`build_longer_spec()` is an exported tidyr function so I didn't override the call).

**Comment by lionel-** [comment]
Ah in this case I think the error would be more informative for end users if you passed the call to `build_longer_spec()`. I think we can conceive of it as a backend function that takes `error_call = current_env()` (instead of `caller_env()`) so that callers may borrow its errors but it's still producing the correct call when called directly.

**Comment by hadley** [comment]
I think that's probably a good idea. We should probably talk through (and write up) exactly when it's appropriate for a function to take an `error_call` argument.

**Comment by lionel-** [comment]
@olivroy contributed support for this in https://github.com/r-lib/tidyselect/pull/350 and https://github.com/r-lib/tidyselect/pull/359
